// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgy3jxmfAm9tbQf5lv8SuGFygwmKuSAew',
    appId: '1:559868633659:web:6d143cbaa6e7c5ec3d321e',
    messagingSenderId: '559868633659',
    projectId: 'maze-game-demo-cbd12',
    authDomain: 'maze-game-demo-cbd12.firebaseapp.com',
    databaseURL: 'https://maze-game-demo-cbd12-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'maze-game-demo-cbd12.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDChp3SUyu9Wydkoa7WCFlQVBe_hkDnoE',
    appId: '1:559868633659:android:9f9aa6c3a007e9d53d321e',
    messagingSenderId: '559868633659',
    projectId: 'maze-game-demo-cbd12',
    databaseURL: 'https://maze-game-demo-cbd12-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'maze-game-demo-cbd12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBed1-_v5UzpXLcw1y7PV2sKUjbtQxCqf8',
    appId: '1:559868633659:ios:bb4ac15ae897f5483d321e',
    messagingSenderId: '559868633659',
    projectId: 'maze-game-demo-cbd12',
    databaseURL: 'https://maze-game-demo-cbd12-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'maze-game-demo-cbd12.appspot.com',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBed1-_v5UzpXLcw1y7PV2sKUjbtQxCqf8',
    appId: '1:559868633659:ios:29f077704ed586813d321e',
    messagingSenderId: '559868633659',
    projectId: 'maze-game-demo-cbd12',
    databaseURL: 'https://maze-game-demo-cbd12-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'maze-game-demo-cbd12.appspot.com',
    iosBundleId: 'com.example.demoApp.RunnerTests',
  );
}
